baseURL = "https://licolnlee.icu"
title = "LicolnLee`s Blog" # 浏览器的标题
languageCode = "en-US" # 语言
hasCJKLanguage = true # 开启可以让「字数统计」统计汉字
theme = "mogege" # 主题 (需要自己下载)

paginate = 11 # 每页的文章数
enableEmoji = true # 支持 Emoji
enableRobotsTXT = true # 支持 robots.txt


preserveTaxonomyNames = true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
  posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "Tools"
    url = "/tools/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/post/"
    weight = 2

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 4

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 5

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 6

[params]
    since = 2017
    author = "LicolnLee"                          # Author's name
    avatar = "/images/me/avatar.jpg"           # Author's avatar
    subtitle = "To improve is to change; to be perfect is to change often."                  # Subtitle
    home_mode = "" # post or other
    enableGitalk = true # gitalk 评论系统

    google_verification = "LA_26dWWc9XmXzNMC2SGM9N4K7-8rN-SY6mWMbQcTiA"

    description = "LicolnLee 的个人博客" # (Meta) 描述
    keywords = "" # site keywords

    beian = ""
    baiduAnalytics = ""
    googleAnalytics = "G-232821020" # Google 统计 id

    license= 'This article uses <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">the Creative Commons Attribution-Non-Commercial Use 4.0 International License Agreement </a>for licensing'

[params.gitalk] # Github: https://github.com/gitalk/gitalk
    clientID = "b56d565392cb74947ee8" # Your client ID
    clientSecret = "992b2bc83a769984ae6fb525a2c07e020f8335b3" # Your client secret
    repo = "licolnlee.github.io" # The repo to store comments
    owner = "Licolnlee" # Your GitHub ID
    admin= "Licolnlee" # Required. Github repository owner and collaborators. (Users who having write access to this repository)
    id= "location.pathname" # The unique id of the page.
    labels= "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage= 15 # Pagination size, with maximum 100.
    pagerDirection= "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually= true # If it is 'false', it is auto to make a Github issue when the administrators login.
    distractionFreeMode= false # Enable hot key (cmd|ctrl + enter) submit comment.
